### ISSUE TITLE
When tables is divided over two pages, there's a problem with the page heading

### ISSUE THREAD

**Issue by MalcolmK** [mauvm/documark-theme-default#1]
Hey,

When a table is automatically divided over two pages, because it does not fit on one page, it collides with the page heading as you can see in the screenshot below.

Malcolm

![image](https://cloud.githubusercontent.com/assets/2427717/6367263/044b37d2-bcd1-11e4-8773-c60ea6f285e3.png)

**Comment by mauvm** [comment]
Hmm, I also noticed this sometimes happens. Probably a wkhtmltopdf issue.

**Comment by mauvm** [comment]
Definitely a wkhtmltopdf issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2182

Closing this issue.

**Comment by RahulDoshi099** [comment]
![image](https://github.com/documark/dmp-theme-default/assets/106651891/bfec14b5-8e43-4cb2-ab5e-9e83020a0669)
![image](https://github.com/documark/dmp-theme-default/assets/106651891/3525e133-c736-4c43-b290-1ce0b0a885a8)


I am getting this same error where i am able to add margin top to table head but when page into second page of pdf its going in with header. Do you have solution for this ?
